# Generated by Django 5.0 on 2024-05-27 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_cashier',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='p2p.listing'),
        ),
    ]
